package com.demo;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lfendy' at '29/07/15 1:18 PM' with Gradle 2.4
 *
 * @author lfendy, @date 29/07/15 1:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
